#!/bin/bash

sudo rm /usr/local/bin/el
rm -r $HOME/.el

# rm $HOME/.history.el

# remove sourcers
sed -i.bak '/# el/,/\.el\.zsh/d' ~/.zshrc
rm ~/.zshrc.bak
sed -i.bak '/# el/,/\.el\.bash/d' ~/.bashrc
rm ~/.bashrc.bak
