#!/bin/bash

if [ -f ~/.el/uninstall ] && ~/.el/uninstall

OS=""

if [ "$(uname)" == "Darwin" ]; then
    OS="darwin"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    OS="linux"
else 
    echo "sorry only linux and darwin are supported"
    exit 1
fi

mkdir -p $HOME/.el
curl -sSL https://github.com/just-hms/elephant/releases/latest/download/el-$OS-amd64.tar.gz | tar -xzf - -C $HOME/.el
sudo mv $HOME/.el/el /usr/local/bin/el

# create the file for the history
touch $HOME/.history.el

## ZSH ---

zsh_file="$HOME/.zshrc"
zsh_sourcer="[ -f ~/.el/.el.zsh ] && source ~/.el/.el.zsh"

if [ -f $zsh_file ] ; then

    if ! grep -q "$zsh_sourcer" ~/.zshrc ; then
        echo "" >> $zsh_file
        echo "# el" >> $zsh_file
        echo $zsh_sourcer >> $zsh_file
    fi;
fi

## BASH ---

bash_file="$HOME/.bashrc"
bash_sourcer="[ -f ~/.el/.el.bash ] && source ~/.el/.el.bash"
bash_precmd_sourcer="[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh"

if [ -f $bash_file ] ; then
    
    if ! grep -q "$bash_sourcer" ~/.bashrc ; then
        echo "" >> $bash_file
        echo "# el" >> $bash_file
        echo $bash_sourcer >> $bash_file
    fi;

    if ! grep -q "$bash_precmd_sourcer" ~/.bashrc ; then

        # pulling bash-preexec.sh
        curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
        echo "" >> $bash_file
        echo "# el dependency" >> $bash_file
        echo $bash_precmd_sourcer >> $bash_file
    fi;
fi

echo "source your .rc file"
